spring:

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  #DEV_DB_CONTAINER
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DEV_DB_HOST}:${DEV_DB_PORT}/${DEV_DB_SCHEMA_NAME}?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: ${DEV_DB_USERNAME}
    password: ${DEV_DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create
    database: mysql
    properties:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      hibernate:
        show_sql: true
        format_sql: true
    generate-ddl: true
    open-in-view: false

app_files:
  fcm_path: src/main/resources/fcm/moiming-b2ae3-firebase-adminsdk-21zjr-11c77c69f7.json

open_api_keys:
  naver_sens_sms: ncp:sms:kr:307383565992:moiming_phone_certi
  naver_access_key_id: rJNU8kRQi1b4Z9QFrCKK
  naver_secret_key_id: 2z0LxdrRcqMCWgADLCTnwlw6SnlYV6YmYK5Z8zzk

file.dir: NOT_NULL