name: Java Gradle CD with Docker

on:
  push:
    branches: [ develop ]

permissions:
  contents: read

env:
  DEV_IMAGE_NAME: dev-moiming-spring-image
  DEV_CONTAINER_NAME: dev-moiming-spring-container

jobs:
  build-docker-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Java 11 Setting
      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      # Gradle Build with Tests
      - name: Gradle Ci
        run: gradle clean build

      # Docker Image Build
      - name: Docker Image Build
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DEV_IMAGE_NAME }} .

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Docker Hub Push
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DEV_IMAGE_NAME }}

  start-dev-container:
    runs-on: ubuntu-latest
    needs: build-docker-image

    steps:
      - name: Executing SSH protocols to send script to Moiming Dev Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEV_SERVER_HOST }}
          username: ubuntu
          key: ${{ secrets.DEV_SERVER_SSH_KEY }}
          script: |
            docker rm -f ${{ env.DEV_CONTAINER_NAME }}
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DEV_IMAGE_NAME }}
            docker run -d -p 8080:8080 --network=dev-moiming-network --name ${{ env.DEV_CONTAINER_NAME }} ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DEV_IMAGE_NAME }}

