name: Java Gradle CD with Docker

on:
  push:
    branches: [ develop ]

permissions:
  contents: read

env:
  DEV_IMAGE_NAME: dev-moiming-spring-image
  DEV_CONTAINER_NAME: dev-moiming-spring-container

jobs:
  build-docker-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Java 11 Setting
      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      # Gradle Build with Tests
      - name: Gradle Ci
        run: gradle clean build

      # Docker Image Build
      - name: Docker Image Build
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DEV_IMAGE_NAME }} .

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Docker Hub Push
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DEV_IMAGE_NAME }}

  start-dev-container:
    runs-on: ubuntu-latest
    needs: build-docker-image

    steps:

      - name: Get Github Action IP
        id: ip
        uses: haythem/public-ip@v1.2

      - name: Setting env variables
        run: |
          echo "AWS_SG_NAME=dev-moiming-sec-group" >> $GITHUB_ENV

      # AWS 권한 획득
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_IAM_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_IAM_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      # 현재 Github Action 의 IP 를 원하는 보안그룹에 22 포트에 추가
      - name: Add Github Actions IP to Security group
        run: |
          aws ec2 authorize-security-group-ingress --group-name ${{ env.AWS_SG_NAME }} --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_IAM_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_IAM_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-northeast-2


      - name: Executing SSH protocols to send script to Moiming Dev Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEV_SERVER_HOST }}
          username: ubuntu
          key: ${{ secrets.DEV_SERVER_SSH_KEY }}
          script: |
            echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
            docker rm -f ${{ env.DEV_CONTAINER_NAME }}
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DEV_IMAGE_NAME }}
            docker run -d -p 8080:8080 --network=dev-moiming-network --name ${{ env.DEV_CONTAINER_NAME }} ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DEV_IMAGE_NAME }}

      # 추가되었던 IP 를 제거한다
      - name: Remove Github Actions IP from security group
        run: |
          aws ec2 revoke-security-group-ingress --group-name ${{ env.AWS_SG_NAME }} --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_IAM_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_IAM_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-northeast-2